### PR TITLE
Add a dockerfile for building without messaging

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by mjgiarlo — COMMENTED** [review]
Can you include a rationale for this PR? I don't see anything concerning in the change set but I'm not clear on how this is valuable. Thanks!

**Comment by jcoyne** [comment]
@mjgiarlo I want to build a docker image for Argo to use so we can stop using jettywrapper.

**Comment by mjgiarlo** [comment]
@jcoyne OK, I get that. How does creating a build with no messaging help us with that? I'm not trying to be obstructionist here, but I want to understand the trade-offs.

**Comment by jcoyne** [comment]
@mjgiarlo so we can use it to run the argo tests: https://github.com/sul-dlss/argo/pull/1187

**Comment by jcoyne** [comment]
@mjgiarlo if you want to keep the messaging, it needs to be able to connect to karaf, which is a separate server.  While this is required for our whole infrastructure, it's not required just to set up argo for dev/testing.

**Review by mjgiarlo — APPROVED** [review]

**Comment by mjgiarlo** [comment]
Sounds good. Thanks, @jcoyne !

**Pull request merged**
